# Generated by Django 4.0 on 2022-01-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulos',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
