# Generated by Django 4.0 on 2022-01-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0002_articulos_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientes',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
