# Generated by Django 4.0 on 2022-01-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0003_rename_dirección_clientes_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tel',
            field=models.CharField(max_length=7, verbose_name='Telefono'),
        ),
    ]
